#server:
#  port: ${SERVER_PORT}
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${DB_BASE_URL}://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: true
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.TomcatJtaPlatform
#        format_sql: true
#        hibernate.use_sql_comments: true
#  jmx:
#    enabled: true
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB
#  web:
#    resources:
#      static-locations: classpath:/templates/
#      add-mappings: on
#  mvc:
#    converters:
#      preferred-json-mapper: jackson
#  thymeleaf:
#    encoding: UTF-8
#    cache: true
#    mode: HTML
#    suffix: .html
#    prefix: classpath:/templates/
#
#management:
#  endpoints:
#    web:
#      base-path: /actuator
#
#logging:
#  level:
#    slf4j: INFO