version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: bers
      POSTGRES_PASSWORD: 123456we
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      DB_BASE_URL: jdbc:postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: bers
      DB_PASSWORD: 123456we
      SERVICE_NAME: app
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - db

volumes:
  db_data: